version: "3.7"

services:

  db:
    image: mysql:8.0
    env_file: config/local.env
    volumes:
      - './docker/mysql_data:/var/lib/mysql'
      - './docker/mysql_init:/docker-entrypoint-initdb.d'
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
